import type { DeviceInfoItem } from "./types";

export const EXAMPLE_DEVICE_INFO: DeviceInfoItem[] = [
  {
    id: "dev-1",
    name: "Chico Cell Modem 01",
    type: "Cell Modem",
    status: "Online",
    battery: "13.6 V",
    solar: "6.2 A",
    signal: "-78 dBm",
    uptime: "99.4%",
    lastSeen: "03/24/26 09:12 AM",
    firmware: "v2.18.4",
    historyAvailable: true,
  },
  {
    id: "dev-2",
    name: "Johnson Edge 02",
    type: "Edge Computer",
    status: "Warning",
    battery: "12.1 V",
    solar: "2.1 A",
    signal: "-91 dBm",
    uptime: "96.2%",
    lastSeen: "03/24/26 09:08 AM",
    firmware: "v1.42.0",
    historyAvailable: false,
  },
  {
    id: "dev-3",
    name: "RTU South Pad",
    type: "RTU",
    status: "Online",
    battery: "24.4 V",
    solar: "4.8 A",
    signal: "-72 dBm",
    uptime: "99.9%",
    lastSeen: "03/24/26 09:10 AM",
    firmware: "v5.2.1",
    historyAvailable: true,
  },
  {
    id: "dev-4",
    name: "Gateway 17A",
    type: "Sensor Gateway",
    status: "Offline",
    battery: "—",
    solar: "—",
    signal: "No Signal",
    uptime: "84.1%",
    lastSeen: "03/23/26 10:41 PM",
    firmware: "v3.7.9",
    historyAvailable: false,
  },
];
