import type { TeamMember, Route } from "./types";

export const ROLE_COLORS: Record<string, string> = {
  Pumper: "#34C759",
  "Field service": "#34C759",
  Superintendent: "#34C759",
  Foreman: "#F59E0B",
  Admin: "#A78BFA",
};

export const EXAMPLE_ROUTES: Route[] = [
  { id: "1", name: "Johnson Route" },
  { id: "2", name: "Union Route" },
  { id: "3", name: "Riordan Route" },
];

export const EXAMPLE_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "1",
    firstName: "Luis",
    lastName: "Marcus",
    name: "Luis Marcus",
    role: "Pumper",
    routeArea: "Chico",
    email: "Johndoe@gmail.com",
    phone: "(405) 555-0128",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "LM",
  },
  {
    id: "2",
    firstName: "Jacob",
    lastName: "Jones",
    name: "Jacob Jones",
    role: "Field service",
    routeArea: "Chico",
    email: "tim.jennings@example.com",
    phone: "(201) 555-0124",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "JJ",
  },
  {
    id: "3",
    firstName: "Wade",
    lastName: "Warren",
    name: "Wade Warren",
    role: "Superintendent",
    routeArea: "-",
    email: "dolores.chambers@example.com",
    phone: "(205) 555-0100",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "WW",
  },
  {
    id: "4",
    firstName: "Dianne",
    lastName: "Russell",
    name: "Dianne Russell",
    role: "Foreman",
    routeArea: "-",
    email: "michelle.rivera@example.com",
    phone: "(217) 555-0113",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "DR",
  },
  {
    id: "5",
    firstName: "Kristin",
    lastName: "Watson",
    name: "Kristin Watson",
    role: "Admin",
    routeArea: "-",
    email: "felicia.reid@example.com",
    phone: "(307) 555-0133",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "KW",
  },
  {
    id: "6",
    firstName: "Cameron",
    lastName: "Williamson",
    name: "Cameron Williamson",
    role: "Foreman",
    routeArea: "-",
    email: "curtis.weaver@example.com",
    phone: "(225) 555-0118",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "CW",
  },
  {
    id: "7",
    firstName: "Ronald",
    lastName: "Richards",
    name: "Ronald Richards",
    role: "Superintendent",
    routeArea: "-",
    email: "alma.lawson@example.com",
    phone: "(239) 555-0108",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "RR",
  },
  {
    id: "8",
    firstName: "Kathryn",
    lastName: "Murphy",
    name: "Kathryn Murphy",
    role: "Admin",
    routeArea: "Chico",
    email: "deanna.curtis@example.com",
    phone: "(201) 555-0124",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "KM",
  },
  {
    id: "9",
    firstName: "Brooklyn",
    lastName: "Simmons",
    name: "Brooklyn Simmons",
    role: "Field service",
    routeArea: "-",
    email: "debra.holt@example.com",
    phone: "(702) 555-0122",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "BS",
  },
  {
    id: "10",
    firstName: "Eleanor",
    lastName: "Pena",
    name: "Eleanor Pena",
    role: "Admin",
    routeArea: "Chico",
    email: "tanya.hill@example.com",
    phone: "(207) 555-0119",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "EP",
  },
  {
    id: "11",
    firstName: "Savannah",
    lastName: "Nguyen",
    name: "Savannah Nguyen",
    role: "Field service",
    routeArea: "-",
    email: "nathan.roberts@example.com",
    phone: "(603) 555-0123",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "SN",
  },
  {
    id: "12",
    firstName: "Marvin",
    lastName: "McKinney",
    name: "Marvin McKinney",
    role: "Admin",
    routeArea: "-",
    email: "willie.jennings@example.com",
    phone: "(808) 555-0111",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "MM",
  },
  {
    id: "13",
    firstName: "Jerome",
    lastName: "Bell",
    name: "Jerome Bell",
    role: "Superintendent",
    routeArea: "-",
    email: "debbie.baker@example.com",
    phone: "(704) 555-0127",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "JB",
  },
  {
    id: "14",
    firstName: "Jane",
    lastName: "Cooper",
    name: "Jane Cooper",
    role: "Admin",
    routeArea: "Chico",
    email: "bill.sanders@example.com",
    phone: "(319) 555-0115",
    company: "Trinity Energy",
    status: "Active",
    assignment: "Johnson Route",
    initials: "JC",
  },
];
