import type { AlarmRow } from "./types";

export const EXAMPLE_ALARMS: AlarmRow[] = [
  {
    id: "1",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    alarmType: "High Level",
    sensorRange: "21 - 41 PSI",
    threshold: "41 PSI",
    recipients: "Operations Team",
    lastValue: "42 PSI",
    status: "Active",
    acked: true,
    history: [
      {
        timestamp: "03/23/26 08:12 AM",
        previousStatus: "Normal",
        nextStatus: "Active",
        note: "Crossed high threshold",
      },
      {
        timestamp: "03/23/26 09:05 AM",
        previousStatus: "Active",
        nextStatus: "Normal",
        note: "Recovered to normal band",
      },
      {
        timestamp: "03/24/26 01:10 AM",
        previousStatus: "Normal",
        nextStatus: "Active",
        note: "Repeated high event",
      },
    ],
  },
  {
    id: "2",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    alarmType: "Low Pressure",
    sensorRange: "21 - 41 PSI",
    threshold: "22 PSI",
    recipients: "Lease Supervisors",
    lastValue: "42 PSI",
    status: "Active",
    acked: true,
    history: [
      {
        timestamp: "03/22/26 07:30 PM",
        previousStatus: "Normal",
        nextStatus: "Active",
      },
      {
        timestamp: "03/22/26 07:55 PM",
        previousStatus: "Active",
        nextStatus: "Normal",
      },
    ],
  },
  {
    id: "3",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    alarmType: "Rate of Change",
    sensorRange: "21 - 41 PSI",
    threshold: "3 PSI / 10 min",
    recipients: "Field Team A",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
    history: [
      {
        timestamp: "03/21/26 03:40 PM",
        previousStatus: "Active",
        nextStatus: "Normal",
        note: "Operator acknowledged and normalized",
      },
    ],
  },
  {
    id: "4",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "5",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "6",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "7",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "8",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "9",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "10",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Active",
    acked: true,
  },
  {
    id: "11",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "12",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Active",
    acked: true,
  },
  {
    id: "13",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "14",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
];
