import type { AlarmRow } from "./types";

export const EXAMPLE_ALARMS: AlarmRow[] = [
  {
    id: "1",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Active",
    acked: true,
  },
  {
    id: "2",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Active",
    acked: true,
  },
  {
    id: "3",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "4",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "5",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "6",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "7",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "8",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "9",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "10",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Active",
    acked: true,
  },
  {
    id: "11",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "12",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Active",
    acked: true,
  },
  {
    id: "13",
    date: "1/23/24",
    asset: "Oil Tank #1",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
  {
    id: "14",
    date: "1/23/24",
    asset: "Water Tank #2",
    lease: "Johnson Lease",
    sensorRange: "21 - 41 PSI",
    lastValue: "42 PSI",
    status: "Normal",
    acked: true,
  },
];
